name: Test Build and Deploy

on:
  push:
    branches:
      - main  # Here source code branch is `master`, it could be other branch
  workflow_dispatch:
  repository_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:

      - name: Clean install dependencies and build
        run: |
          sudo apt-get update && sudo apt-get install -y libvips42

      - uses: actions/checkout@v2
        with:
          fetch-depth: zero

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Actions' cache to cache site on servers
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('**/_data/picture.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: setup git config
        run: |
          git clone https://github.com/datapolitical/chrisfnicholson.github.io.git

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: datapolitical/jekyll-deploy-action@master
        with:
          provider: 'github'
          token: "${{ secrets.GITHUB_TOKEN }}" # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './chrisfnicholson.github.io'           # Default is root directory
          jekyll_cfg: '_config.yml,_config_dev.yml'  # Default is _config.yml
          jekyll_baseurl: '/cfndev.github.io'         # Default is according to _config.yml
          bundler_ver: '>=0'         # Default is latest bundler version
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: 'pacman -S --noconfirm imagemagick libwebp'
